### ISSUE TITLE
Down migration fails trying to delete an index that doesn't exist

### ISSUE THREAD

**Issue by matteocontrini** [FriendsOfFlarum/byobu#160] opened 2021-09-30 19:50 UTC
## Bug Report

**Current Behavior**

When trying to run "down" migrations after clicking "Uninstall" on the admin page, the operation fails with:

```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'users_unified_index_with_byobu_index'; check that column/key exists
```

The stack trace reveals the index is:

```
#8 /usr/local/openresty/nginx/html/flarum1/vendor/fof/byobu/migrations/2021_01_13_000000_unified_index_index.php(25): Illuminate\Database\Schema\Builder->table('users', Object(Closure))
```

And then it's impossible to recover from the admin panel because enabling the extension doesn't work either.

**Steps to Reproduce**

1. Install the extension, enable it
2. Disable it
3. Attempt to "uninstall" it from the admin panel

**Environment**
- Flarum version: 1.0.3
- Extension version: 1.0.0
- Hosting environment: local
- PHP version: 7.3.29

**Comment by BBaoVanC** [comment] 2022-04-28 01:22
I'm getting this too.

**Comment by clarkwinkelmann** [comment] 2022-05-02 12:16
Thanks for the report. I can confirm the issue is reproducible all of the time, if all the migrations were previously applied.

I have created a PR to fix this issue. I'll try to get it merged in the next few days.

The workarounds are indeed to either re-create the missing index so Flarum can delete it again, or drop `2021_01_13_000000_unified_index_index` from the list or migrations in the `migrations` table to tell Flarum the index has already been removed.

**Closed** 2022-05-13 20:40 UTC
Labels: bug
