### ISSUE TITLE
Normal user who is alone in private discussion can't left or delete it

### ISSUE THREAD

**Issue by bryantmilan** [FriendsOfFlarum/byobu#128] opened 2020-07-12 21:19 UTC
UserA started private discussion with UserB and after a while UserA left private discussion. UserB is now alone in private discussion and he is not able to left or delete that private discussion. What is the problem?

**Comment by clarkwinkelmann** [comment] 2020-07-14 22:01
I'm not sure what our intended behavior was here. Maybe someone else from the team will be able to shine some light.

What would make the most sense for you?

If you're alone in a private discussion, being deleted or not won't technically change anything. Users can't permanently delete discussions anyway, so this would just add the trash icon and nothing else.

I'm not sure if it's intentional to be able to have just one user left in a discussion though. To me it would make sense to have a minimum of two recipients.

**Comment by bryantmilan** [comment] 2020-07-15 11:56
I will attach some screenshots of what it looks like so you could better understand the issue. I’m not a programmer, but I think it would be great if a user who was left alone in a private discussion could leave the discussion and then will that private discussion automatically be deleted forever. The issue is not of a technical nature, but in fact, as can be seen on the screenshots, the user in the list of private discussions will see that discussion in which he is alone and which no longer has any purpose because the user will not talk to himself in that discussion. The other user who created that discussion and who left it earlier won't see that private discussion anymore. I don't know how else I could explain this, but it's a really small issue that is very noticeable to normal users.

1. This is screenshot from a list of private discussions.
![Screenshot_1](https://user-images.githubusercontent.com/66064259/87541937-69305c00-c6a2-11ea-9ddd-9b81f7cf6fd0.png)

2. This is screenshot within the private discussion.
![Screenshot_2](https://user-images.githubusercontent.com/66064259/87541939-69c8f280-c6a2-11ea-838c-39896e20c90c.png)

3. These are the options that the user who is left alone has.
![Screenshot_3](https://user-images.githubusercontent.com/66064259/87541940-6a618900-c6a2-11ea-8a52-4cba93dbbb90.png)

**Comment by luceos** [comment] 2020-11-21 17:41
This will be fixed in the next release.

**Closed by luceos** 2020-11-21 17:41 UTC
