### ISSUE TITLE
No content displayed when enabling this extension.

### ISSUE THREAD

**Issue by tazzytazzy** [FriendsOfFlarum/byobu#193] opened 2023-12-16 19:36 UTC
## Bug Report

**Current Behavior**
When I enable this extension, there's no content displayed.
A clear and concise description of the behavior.

**Steps to Reproduce**
1. Enable this plugin through the admin panel.
2. Go back to the flarum forum
3. No content.

**Expected Behavior**
Show the flarum message board.

**Screenshots**

**Environment**
- Flarum version: 1.8.4
- Extension version: 1.3.1
- Website URL: https://dcctalk.com
- Webserver: apache, behind haproxy, varnish, and cloudflare tunnel.
- Hosting environment: vps
- PHP version: 7.4
- Browser: Any

```
Flarum core: 1.8.4
PHP version: 7.4.33
MySQL version: 11.1.3-MariaDB-1:11.1.3+maria~ubu2204-log
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, luasandbox, exif, msgpack, mysqli, pdo_mysql, Phar, posix, readline, redis, scrypt, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wikidiff2, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache
+-----------------------+---------+--------+
| Flarum Extensions     |         |        |
+-----------------------+---------+--------+
| ID                    | Version | Commit |
+-----------------------+---------+--------+
| flarum-tags           | v1.8.0  |        |
| flarum-flags          | v1.8.0  |        |
| flarum-suspend        | v1.8.1  |        |
| v17development-seo    | v1.8.0  |        |
| maicol07-sso          | 1.11.5  |        |
| fof-terms             | 1.3.0   |        |
| fof-split             | 1.1.1   |        |
| fof-sitemap           | 1.0.3   |        |
| fof-reactions         | 1.3.4   |        |
| fof-nightmode         | 1.5.3   |        |
| fof-merge-discussions | 1.4.1   |        |
| fof-links             | 1.2.1   |        |
| fof-gamification      | 1.6.7   |        |
| fof-formatting        | 1.0.3   |        |
| fof-best-answer       | 1.4.1   |        |
| fof-analytics         | 1.1.0   |        |
| flarum-subscriptions  | v1.8.0  |        |
| flarum-sticky         | v1.8.0  |        |
| flarum-statistics     | v1.8.0  |        |
| flarum-mentions       | v1.8.2  |        |
| flarum-markdown       | v1.8.0  |        |
| flarum-lock           | v1.8.0  |        |
| flarum-lang-english   | v1.8.0  |        |
| flarum-emoji          | v1.8.0  |        |
| flarum-bbcode         | v1.8.0  |        |
| askvortsov-categories | v3.0.9  |        |
+-----------------------+---------+--------+

```

**Additional Context**
Browser console shows this error:

mount-redraw.js:15 TypeError: Cannot read properties of undefined (reading 'type')
    at e.pushObject (Store.ts:125:27)
    at e.pushPayload (Store.ts:103:110)
    at e.preloadedApiDocument (Application.tsx:363:22)
    at n.loadPage (DiscussionListState.ts:43:34)
    at e.refresh (PaginatedListState.ts:157:17)
    at e.refreshParams (PaginatedListState.ts:142:19)
    at n.oninit (IndexPage.tsx:46:5)
    at Function.a (render.js:30:16)
    at M (render.js:917:53)
    at render.js:153:3

**Comment by imorland** [comment] 2023-12-16 23:18
Version `1.3.1` was the last version of this extension to support PHP 7.x, and we don't have any plans to continue support as this is now EOL.

For PHP 7.4 support, I suggest using `1.3.0`, as `1.3.1` has a known issue on PHP7. 

Better still, if you are in a position to update your PHP version, you'll be able to benefit from ongoing development on this and other FoF extensions.

**Comment by DavideIadeluca** [comment] 2024-06-15 13:27
Thanks @tazzytazzy for your bug report. As @imorland mentioned, we don't offer support for versions which depend on a PHP version with ended security support. As I'm unable to reproduce your described issue on the latest version, I'm closing this issue. Please open a new issue if you can reproduce it on the latest version of `fof/byobu`.

**Closed by DavideIadeluca** 2024-06-15 13:27 UTC
Labels: bug
